
#ifndef _ROSYSTEMCONSTANTS_
#define _ROSYSTEMCONSTANTS_

#define FLUSH_TIMER_MS 300000
#define PUMP_INLET_DELAY_MS 5000
#define PUMP_FREQUENCY_MS 500000 // Default
#define FILL_START_DISTANCE_CM 160
#define FILL_STOP_DISTANCE_CM 40
#define PUMP_RUN_MIN_TO_FLUSH 2
#define WARNING_DELAY 60000
#define COMPONENT_NAME "ro-system"

#endif
