#ifndef _BAROMETERCONSTANTS_
#define _BAROMETERCONSTANTS_

#define COMPONENT_NAME "Barometer"
#define DISPLAY_NAME COMPONENT_NAME
#define UPDATE_PERIOD 10000UL
#define FULL_PRESSURE_DEFAULT 10000
#define OPTION_FULL_PRESSURE "Full Pressure"
#define OPTION_PRESSURE "Pressure"

#endif
