version: '3.9'
services:
  mongo:
    container_name: romcon_mongo
    image: mongo:4.4.11
    restart: always
    environment:
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - romcon_mongo_volume:/data/db
    ports:
      - "27017:27017"
  
  stream:
    container_name: romcon_stream
    depends_on: 
      - mongo
    build: ./streamService
    image: ${DOCKER_USERNAME}/romcon-stream
    restart: always
    environment: 
      - PARTICLE_USERNAME=${PARTICLE_USERNAME}
      - PARTICLE_PASSWORD=${PARTICLE_PASSWORD}
      - MONGODB_URI=romcon_mongo
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
  
  backend:
    container_name: romcon_backend
    depends_on:
      - mongo
    build: ./backend
    image: ${DOCKER_USERNAME}/romcon-backend
    restart: always
    ports: 
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment: 
      - PORT=${BACKEND_PORT}
      - PARTICLE_USERNAME=${PARTICLE_USERNAME}
      - PARTICLE_PASSWORD=${PARTICLE_PASSWORD}
      - MONGODB_URI=romcon_mongo
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - API_SECRET=${API_SECRET}
  
  frontend:
    container_name: romcon_frontend
    depends_on:
      - backend
    build: ./frontend
    image: ${DOCKER_USERNAME}/romcon-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"

volumes:
  romcon_mongo_volume:
