version: '3.9'
services:
  mongo:
    container_name: romcon_mongo
    image: mongo:4.4.11
    restart: always
    environment:
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - romcon_mongo_volume:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    container_name: romcon_rabbitmq
    restart: always
    build: ./rabbitmq
    image: ${DOCKER_USERNAME}/romcon-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${MQTT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${MQTT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
    volumes:
      - romcon_rabbitmq_volume_data:/var/lib/rabbitmq/
      - romcon_rabbitmq_volume_logs:/var/log/rabbitmq
  
  stream:
    container_name: romcon_stream
    depends_on: 
      - mongo
      - rabbitmq
    build: ./streamService
    image: ${DOCKER_USERNAME}/romcon-stream
    restart: always
    environment: 
      - PARTICLE_USERNAME=${PARTICLE_USERNAME}
      - PARTICLE_PASSWORD=${PARTICLE_PASSWORD}
      - MONGODB_URI=romcon_mongo
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
  
  backend:
    container_name: romcon_backend
    depends_on:
      - mongo
      - rabbitmq
    build: ./backend
    image: ${DOCKER_USERNAME}/romcon-backend
    restart: always
    ports: 
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment: 
      - PORT=${BACKEND_PORT}
      - PARTICLE_USERNAME=${PARTICLE_USERNAME}
      - PARTICLE_PASSWORD=${PARTICLE_PASSWORD}
      - MONGODB_URI=romcon_mongo
      - MONGODB_DB_NAME=${MONGODB_DB_NAME}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - API_SECRET=${API_SECRET}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
  
  frontend:
    container_name: romcon_frontend
    depends_on:
      - backend
    build: ./frontend
    image: ${DOCKER_USERNAME}/romcon-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:80"

  discovery:
    container_name: romcon_discovery
    build: ./mqttDiscoveryService
    image: ${DOCKER_USERNAME}/romcon-discovery
    restart: always
    ports:
      - "1882:1882"
    environment:
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}

volumes:
  romcon_mongo_volume:
  romcon_rabbitmq_volume_data:
  romcon_rabbitmq_volume_logs:
