version: '3.9'
services:

  rabbitmq:
    container_name: romcon_rabbitmq
    restart: always
    build: ./rabbitmq
    image: ${DOCKER_USERNAME}/romcon-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${MQTT_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${MQTT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
      - "1883:1883"
    volumes:
      - romcon_rabbitmq_volume_data:/var/lib/rabbitmq/
      - romcon_rabbitmq_volume_logs:/var/log/rabbitmq

  discovery:
    container_name: romcon_discovery
    build:
      context: .
      dockerfile: ./MQTT_Discovery_Service/Dockerfile
    image: ${DOCKER_USERNAME}/romcon-discovery
    restart: always
    ports:
      - "1882:1882/udp"
    environment:
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_OVERRIDE

  capture:
    container_name: romcon_capture
    depends_on:
      - rabbitmq
    build:
      context: .
      dockerfile: ./MQTT_Capture_Service/Dockerfile
    image: ${DOCKER_USERNAME}/romcon-capture
    restart: always
    environment:
      - SUPABASE_URL
      - SUPABASE_KEY
      - PARTICLE_API_KEY
      - MQTT_USERNAME
      - MQTT_PASSWORD
      - MQTT_OVERRIDE

volumes:
  romcon_mongo_volume:
  romcon_rabbitmq_volume_data:
  romcon_rabbitmq_volume_logs:
