#ifndef _GLOBAL_DEFINES_
#define _GLOBAL_DEFINES_

#define VERSION_STRING "1.0.0-beta"
#define FEATURE_FLOATSWITCH
//#define FEATURE_ULTRASONIC
//#define FEATURE_FLOATMETER
//#define TESTING 1

#endif
