name: docker

on:
  push:
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: MQTT Discovery Service (Build & Push)
        uses: docker/build-push-action@v4
        with:
          context: ./WebApp
          file: ./WebApp/MQTT_Discovery_Service/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/romcon-discovery:latest,${{ secrets.DOCKERHUB_USERNAME }}/romcon-discovery:${{ github.ref_name }}
      -
        name: MQTT Capture Service (Build & Push)
        uses: docker/build-push-action@v4
        with:
          context: ./WebApp
          file: ./WebApp/MQTT_Capture_Service/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/romcon-capture:latest,${{ secrets.DOCKERHUB_USERNAME }}/romcon-capture:${{ github.ref_name }}
      -
        name: Rabbit MQ Service (Build & Push)
        uses: docker/build-push-action@v4
        with:
          context: ./WebApp
          file: ./WebApp/rabbitmq/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/romcon-rabbitmq:latest,${{ secrets.DOCKERHUB_USERNAME }}/romcon-rabbitmq:${{ github.ref_name }}
      -
        name: App (Build & Push)
        uses: docker/build-push-action@v4
        with:
          context: ./WebApp
          file: ./WebApp/app/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/romcon-app:latest,${{ secrets.DOCKERHUB_USERNAME }}/romcon-app:${{ github.ref_name }}
